opensuse-leap: add missing python3 package for sqlite3
In the tpm2-pkcs11 CI we see this error:

+ tpm2_ptool init --primary-auth=mypobjpin --path=/tmp/tpm_simulator_yi0Bu2
Traceback (most recent call last):
  File "<frozen runpy>", line 203, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 6, in <module>
    from .commandlets_store import InitCommand  # pylint: disable=unused-import # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_store.py", line 12, in <module>
    from .db import Db
  File "/workspace/tpm2-pkcs11/tools/tpm2_pkcs11/db.py", line 6, in <module>
    import sqlite3
  File "/usr/lib64/python3.13/_import_failed/sqlite3.py", line 16, in <module>
                raise ImportError(f"""Module '{failed_name}' is not installed.
    ...<2 lines>...
    to install it.""")
ImportError: Module 'sqlite3' is not installed.
Use:
  sudo zypper install python313
to install it.

python3-pip is already in -dev, remove it to avoid redundancy.

Signed-off-by: Moritz Buhl <moritz.buhl@infineon.com>